[package]
name = "easytime"
version = "0.1.2"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/easytime"
homepage = "https://github.com/taiki-e/easytime"
documentation = "https://docs.rs/easytime"
keywords = ["no_std", "time"]
categories = ["no-std"]
readme = "README.md"
description = """
Providing wrapper types for safely performing panic-free checked arithmetic on instants and durations.
"""

[workspace]

[features]
default = ["std"]
std = []
# TODO
# system_time = ["std"]
